# Generated by Django 5.2.5 on 2025-09-06 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
