# Generated by Django 5.2.5 on 2025-09-04 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_options_remove_student_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoursControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_required', models.IntegerField(default=80)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='control_horas', to='students.student')),
            ],
        ),
    ]
