# Generated by Django 5.1 on 2025-10-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_estudiante_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/estudiantes/', verbose_name='Foto de Perfil'),
        ),
    ]
