# Generated by Django 5.2.5 on 2025-10-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_estudiante_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ControlHoras',
        ),
    ]
