# Generated by Django 5.2.5 on 2025-09-06 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cargo', models.CharField(blank=True, help_text='Position of the teacher (e.g: Professor, Coordinator, Director)', max_length=100, null=True)),
                ('grado', models.CharField(blank=True, help_text='Student grade (e.g: 1st, 2nd, 3rd)', max_length=50, null=True)),
                ('docente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.docente')),
                ('estudiante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.estudiante')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='accounts.rol')),
            ],
        ),
    ]
