# Generated by Django 5.2.5 on 2025-09-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, help_text='( Professor, Coordinator, Director)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='grado',
            field=models.CharField(blank=True, help_text='Si es estudiante', max_length=50, null=True),
        ),
    ]
