# Generated by Django 5.2.5 on 2025-09-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_usuario_cargo_alter_usuario_grado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='grado',
            field=models.CharField(blank=True, choices=[('A', 'Grupo A'), ('B', 'Grupo B'), ('C', 'Grupo C'), ('D', 'Grupo D')], max_length=1, null=True),
        ),
    ]
