# Generated by Django 5.2.5 on 2025-09-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usuario_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='grupo',
            field=models.CharField(blank=True, choices=[('A', 'Grupo A'), ('B', 'Grupo B'), ('C', 'Grupo C'), ('D', 'Grupo D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='grado',
            field=models.CharField(blank=True, choices=[('11', ' Once'), ('10', 'Decimo')], max_length=2, null=True),
        ),
    ]
