# Generated by Django 5.2.5 on 2025-09-01 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE accounts_user DROP COLUMN IF EXISTS is_superuser;',
            reverse_sql='ALTER TABLE accounts_user ADD COLUMN is_superuser BOOLEAN DEFAULT FALSE;',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE accounts_user DROP COLUMN IF EXISTS is_staff;',
            reverse_sql='ALTER TABLE accounts_user ADD COLUMN is_staff BOOLEAN DEFAULT FALSE;',
        ),
    ]
