# Generated by Django 5.2.5 on 2025-09-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_user_last_login_user_cargo_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='grado',
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, help_text='Student grade (e.g: 1st, 2nd, 3rd)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, help_text='Position of the teacher (e.g: Professor, Coordinator, Director)', max_length=100, null=True),
        ),
    ]
