# Generated by Django 5.1 on 2025-09-05 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_user_cargo_remove_user_grado_user_grade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='usuario',
        ),
    ]
