# Generated by Django 5.2.5 on 2025-10-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_docente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/estudiantes/', verbose_name='Foto de Perfil'),
        ),
    ]
