# Generated by Django 5.2.5 on 2025-10-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_docente_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/docentes/', verbose_name='Foto de Perfil'),
        ),
    ]
