# Generated by Django 5.2.5 on 2025-09-06 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidence', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.TextField()),
                ('aprobada', models.BooleanField(default=False)),
                ('fecha_validacion', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='evidence.actividad')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validaciones', to='teachers.docente')),
            ],
        ),
    ]
