# Generated by Django 5.2.5 on 2025-09-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validacion',
            name='aprobada',
        ),
        migrations.AddField(
            model_name='validacion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=10),
        ),
    ]
