# Generated by Django 5.2.5 on 2025-09-30 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_validacion_aprobada_validacion_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validacion',
            name='docente',
        ),
    ]
