# Generated by Django 5.1 on 2025-09-19 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_remove_actividad_estudiante_actividad_creador'),
        ('institutions', '0010_remove_encargado_estudiante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='institutions.encargado'),
        ),
    ]
