# Generated by Django 5.2.5 on 2025-09-09 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institucion',
            name='nombre_contacto',
        ),
    ]
