# Generated by Django 5.1 on 2025-09-17 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_encargado_creador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encargado',
            name='institucion',
        ),
    ]
