# Generated by Django 5.1 on 2025-09-18 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_remove_encargado_institucion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encargado',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='institucion',
            name='creador',
        ),
        migrations.AddField(
            model_name='encargado',
            name='creador_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encargados_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institucion',
            name='creador_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instituciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
