# Generated by Django 5.1 on 2025-09-18 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0006_remove_encargado_creador_remove_institucion_creador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encargado',
            old_name='creador_id',
            new_name='creador',
        ),
        migrations.RenameField(
            model_name='institucion',
            old_name='creador_id',
            new_name='creador',
        ),
    ]
