# Generated by Django 5.1 on 2025-09-18 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_rename_creador_id_encargado_creador_and_more'),
        ('students', '0002_rename_apellido_estudiante_apellidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institucion',
            name='creador',
        ),
        migrations.AddField(
            model_name='institucion',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institucion', to='students.estudiante'),
        ),
    ]
