# Generated by Django 5.2.5 on 2025-09-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0010_remove_encargado_estudiante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='barrio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
