# Generated by Django 5.2.5 on 2025-09-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0011_institucion_barrio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institucion',
            name='telefono_contacto',
        ),
    ]
