# Generated by Django 5.2.5 on 2025-09-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0012_remove_institucion_telefono_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
