# Generated by Django 5.2.5 on 2025-09-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0013_institucion_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='encargado',
            name='observaciones',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
